/**
 * Post-build script: inject PWA manifest link and Apple PWA meta tags into
 * the static index.html generated by `expo export --platform web`.
 *
 * This is needed because Expo's `output: "single"` mode does not emit a
 * web app manifest by itself. The manifest itself is shipped via the
 * `public/` directory which Expo copies to `dist/` as-is.
 */
const fs = require('node:fs');
const path = require('node:path');

const distDir = path.join(__dirname, '..', 'dist');
const indexPath = path.join(distDir, 'index.html');

if (!fs.existsSync(indexPath)) {
  console.error(`postbuild: ${indexPath} not found. Did the build run?`);
  process.exit(1);
}

const tags = `
  <link rel="manifest" href="/manifest.webmanifest" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="default" />
  <meta name="apple-mobile-web-app-title" content="낱말 카드" />
  <link rel="apple-touch-icon" href="/icons/icon-192.png" />
  <link rel="apple-touch-icon" sizes="512x512" href="/icons/icon-512.png" />
  <meta name="format-detection" content="telephone=no" />
  <meta name="mobile-web-app-capable" content="yes" />
`;

let html = fs.readFileSync(indexPath, 'utf8');

const swRegister = `
  <script>
    if ('serviceWorker' in navigator) {
      window.addEventListener('load', function() {
        navigator.serviceWorker.register('/sw.js');
      });
    }
  </script>
`;

const errorReporter = `
  <script>
    window.onerror = function(msg, src, line, col, err) {
      var d = document.createElement('div');
      d.style.cssText = 'position:fixed;top:0;left:0;right:0;padding:16px;background:red;color:#fff;font:14px monospace;z-index:99999;white-space:pre-wrap;';
      d.textContent = 'ERROR: ' + msg + '\\nFile: ' + src + '\\nLine: ' + line + ':' + col + '\\n' + (err && err.stack ? err.stack : '');
      document.body.appendChild(d);
    };
    window.addEventListener('unhandledrejection', function(e) {
      var d = document.createElement('div');
      d.style.cssText = 'position:fixed;top:0;left:0;right:0;padding:16px;background:red;color:#fff;font:14px monospace;z-index:99999;white-space:pre-wrap;';
      d.textContent = 'REJECTION: ' + (e.reason && e.reason.stack ? e.reason.stack : e.reason);
      document.body.appendChild(d);
    });
  </script>
`;

if (html.includes('rel="manifest"')) {
  console.log('postbuild: manifest tag already present, skipping injection.');
} else {
  html = html.replace('</head>', `${tags}</head>`);
  console.log('postbuild: injected PWA manifest + Apple meta tags into index.html');
}

if (!html.includes('window.onerror')) {
  html = html.replace('<div id="root">', `${errorReporter}<div id="root">`);
  console.log('postbuild: injected error reporter');
}

if (!html.includes('serviceWorker.register')) {
  html = html.replace('</body>', `${swRegister}</body>`);
  console.log('postbuild: injected service worker registration');
}

fs.writeFileSync(indexPath, html);
